name: DiscordSRV-Alerts
version: @VERSION@
main: com.discordsrv.alerts.bukkit.AlertsBukkitBootstrap
api-version: "1.13"
softdepend: [DiscordSRV-Ascension]

commands:
  discordsrvalerts:
    aliases: [dsrva, alerts]