name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed for dependency graph

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Checkout Ascension
        uses: actions/checkout@v6
        with:
          repository: 'DiscordSRV/Ascension'
          path: 'ascension'
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          # caching handled by setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: Publish Ascension to Maven Local
        run: cd ascension && ./gradlew api:publishToMavenLocal api:api-configurate:publishToMavenLocal
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Build Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: "bukkit/build/libs/DiscordSRV-Alerts*.jar"
      - name: Generate and submit dependency graph
        if: github.event_name == 'push'
        uses: gradle/actions/dependency-submission@v6